version: '3'

services:
  #mysql
    db:
      image: mysql:latest
      container_name: cafeweb
      columes:
      - src:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: 1234
      networks:
      - dev_network
   #phpmyadmin
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: myadmin
      ports:
      - '8080:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: 1234
      networks:
      - dev_network
    
    adminer:
      depends_on:
      - db
      image: adminer:latest
      container_name: bryan
      environment:
        ADMINER_DEFAULT_SERVER: db
      ports:
      - 8085:8080
      networks:
      - dev_network

    networks:
      dev_network:

    volumes:
        src:
